### ISSUE TITLE
Issue with mediainfo (in flood and cli) and the fix

### ISSUE THREAD

**Issue by WuSiYu** [hotio/qflood#6]
First, appreciate for this work, this container/app is a awesome solution to have flood + qb on my unraid machine.
But I found that in the flood ui when double-click a download and view the "MediaInfo" tab, it not work and report the error like this (FYI, my environment is Unraid 6.10.3):
```
Command failed: mediainfo /dl/<somefile>.mkv
Error relocating /usr/lib/libmediainfo.so.0: _ZSt28__throw_bad_array_new_lengthv: symbol not found
```
It has the similar error when invoking the `mediainfo` command directly from container's console too. So this issue is related to the mediainfo installs itself. It looks like a C/C++ runtime library mismatch.

After some searching I found the solution is run the following command in container to update the alpine's C/C++ runtime:
```
apk -UvX http://dl-cdn.alpinelinux.org/alpine/edge/main add -u mediainfo
```
After that the mediainfo will works normally and the other stuffs seem not been broken too. (I haven't tested the VPN feature since I'm not using it)

So I think you may like to add that command into the Dockerfile after further testing.

**Comment by mrhotio** [comment]
give the updated image another try
