### ISSUE TITLE
Cannot connect to the client

### ISSUE THREAD

**Issue by h4wwk3ye** [hotio/qflood#7]
In the latest image flood is not able to connect to qbittorrent client, thought qbittorrent works fine. Rolled back to `hotio/qflood:release-8c5d56f` and it's working fine.

**Comment by mrhotio** [comment]
Qbit changed stuff, qflood needs an update, out of my hands

**Comment by techie2000** [comment]
For anyone coming across this, I switched (back) to hotio/qflood:release-4.4.3.1--4.7.0 to get normal service resumption. You will get auth errors in the log if use :latest

**Comment by Nedlinin** [comment]
jesec/flood/pull/594 appears to fix this once it gets merged.

**Comment by hongkongkiwi** [comment]
Merged now! Can we get an updated container?

**Comment by mrhotio** [comment]
It's not released yet, when it's released you'll get an updated container, all automatic

**Comment by Nedlinin** [comment]
@mrhotio : Any chance of just releasing a version based on the master branch of flood + qbittorrent 4.4.5?

**Comment by mrhotio** [comment]
no
